name: generate
on:
  workflow_dispatch:
permissions:
  contents: read
  packages: write
defaults:
  run:
    shell: bash
jobs:
  release:
    strategy:
      matrix:
        version: [v1, v2]
        image_size: [10MB, 100MB, 1GB]
        layer_count: [1, 4]
    runs-on: ubuntu-latest
    steps:
      - name: Setup benchmark
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 #v3.0.0
        with: 
          repo: spegel-org/benchmark
      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 #v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate image
        run: benchmark generate --layer-count ${{ matrix.layer_count }} --image-size "${{ matrix.image_size }}" --image-name ghcr.io/${{ github.repository_owner }}/benchmark:${{ matrix.version }}-${{ matrix.image_size }}-${{ matrix.layer_count }}
      - name: Publish image
        run: docker push ghcr.io/${{ github.repository_owner }}/benchmark:${{ matrix.version }}-${{ matrix.image_size }}-${{ matrix.layer_count }}
